### ISSUE TITLE
BP Launcher Download fails on Demo

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp-cdn#157] opened 2019-07-19 20:33 UTC
Something is seriously messed up on Demo v1.2.458.  Strangely, the same thing works perfectly on Production v1.2.458 and on Solo 1.3.461 on the same computer, at the same time (all three sites open and connected to same BP Launcher).

I've tested this on Windows and Mac.  Same result on both systems.

On Production and Solo, a download results in this successful output to the user:
![image](https://user-images.githubusercontent.com/1266318/61563565-1ee1b400-aa29-11e9-8442-9995664e6d65.png)

On Demo (nothing else changed), a download results in this failed and confusing output for the user:
![image](https://user-images.githubusercontent.com/1266318/61563611-35880b00-aa29-11e9-91c0-d7e1c95d12f8.png)

Trying again results in this:
![image](https://user-images.githubusercontent.com/1266318/61563625-3d47af80-aa29-11e9-9370-89f0cbac87f2.png)

The BP Launcher console output is:
![image](https://user-images.githubusercontent.com/1266318/61563666-5cded800-aa29-11e9-8676-a5cfed0efd53.png)

Which makes me think that it's receiving two download requests in quick succession from the Demo tab.

Since it works great on Production and Solo, I'm led to believe that it's not something wrong in BP Launcher.

**Comment by PropGit** [comment] 2019-07-19 20:35
Another disturbing thing is that Production and Demo are supposedly running the exact same version of BlocklyProp Cloud.

**Comment by zfi** [comment] 2019-07-23 22:55
The Cloud Compiler should be the same release number in demo and production. There is a new update the uses Python 3 that will be released in containers in early August. 

I think the issue is caused by recent changes in the CDN code. This should be readily identified in dev with the either the dev VM or the container collection.

**Closed** 2019-11-16 03:17 UTC
Labels: bug
